FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npx prisma migrate reset --force

RUN npx prisma generate

RUN npx prisma db seed

CMD ["npm", "start"]
